http:
  middlewares:
    crowdsec-bouncer:
      plugin:
        bouncer:
          enabled: true          
          crowdsecLapiHost: crowdsec:8080
          crowdsecMode: live
          crowdsecLapiKey: # à générer avec docker compose exec crowdsec cscli bouncers add traefik-bouncer ou kubectl ...